CREATE OR REPLACE FUNCTION block_id_updates()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id THEN
        RAISE EXCEPTION 'IT IS A PRANK. KALA MO MABABAGO MO HA';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;